[workspace]
resolver = "2"

members = [
    "./src"
    # "./timelock_auction/erc721",
    # "./timelock_auction/vickrey_auction",
    # "./timelock_auction/tlock_proxy",
    # "./examples/bit-roulette",
    # "./examples/transmutation",
    # "./examples/world-registry",
]